name: Collect Issues

on:
  workflow_dispatch:
      
jobs:

  run-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.6

    - name: Set up Python
      uses: actions/setup-python@v5.1.0
      with:
        python-version: '3.x'

    - name: Create repos_dir
      run: |
        mkdir -p repos_dir

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install pydriller

    - name: Collect Issues
      env:
        API_TOKEN_1: ${{ secrets.GET_ISSUES_1 }}
        API_TOKEN_2: ${{ secrets.GET_ISSUES_2 }}
        API_TOKEN_3: ${{ secrets.GET_ISSUES_3 }}
        API_TOKEN_4: ${{ secrets.GET_ISSUES_4 }}
        API_TOKEN_5: ${{ secrets.GET_ISSUES_5 }}
        API_TOKEN_6: ${{ secrets.GET_ISSUES_6 }}
        API_TOKEN_7: ${{ secrets.GET_ISSUES_7 }}
        API_TOKEN_8: ${{ secrets.GET_ISSUES_8 }}
        API_TOKEN_9: ${{ secrets.GET_ISSUES_9 }}
        API_TOKEN_10: ${{ secrets.PRANALIZER }}
      run: |
        python collect_issues.py

    - name: Remove content from repos_dir/
      run:
        rm -rf repos_dir/*

    - name: Commit and push
      run: |
        git config --global user.email "thiagogquinto.dev@gmail.com"
        git config --global user.name "Thiago Quinto"
        git pull 
        git add .
        git commit -m "Add Issues from repositories"
        git push
