name: Collect Issues

on:
  workflow_dispatch:
      
jobs:

  run-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.6

    - name: Set up Python
      uses: actions/setup-python@v5.1.0
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        
    - name: Collect Issues
      env:
        API_TOKEN: ${{ secrets.GET_ISSUES }}
      run: |
        python get_issues.py

    - name: Commit and push
      run: |
        git config --global user.email "thiagogquinto.dev@gmail.com"
        git config --global user.name "Thiago Quinto"
        git pull 
        git add .
        git commit -m "Add Issues from repositories"
        git push
