name: Solidify data

on:
  workflow_dispatch:
      
jobs:

  run-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.6

    - name: Create folders and clone repositories
      run: |
        mkdir -p repos_dir
        cd repos_dir
        git clone https://github.com/JabRef/jabref.git
      
    - name: Set up Python
      uses: actions/setup-python@v5.1.0
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install pyvis
        pip install networkx
        pip install matplotlib
        pip install numpy
        
    - name: Run PRAnalyzer
      working-directory: PRANALYZER/
      env:
       API_TOKEN: ${{ secrets.PRANALIZER }}
      run: |
        python run_analyses.py

    - name: Calculate cases by tests made
      run: |
        python confusion_matrix.py

    # - name: Check BIC records
    #   run: |
    #     python count_bics.py

    # - name: Check SZZ algorithms
    #   run: |
    #     python count_by_bic_method.py

    - name: Track commit path
      working-directory: relations/
      run: |
        python get_commit_path.py
        python create_network.py

    - name: Commit and push
      run: |
        git config --global user.email "thiagogquinto.dev@gmail.com"
        git config --global user.name "Thiago Quinto"
        git pull 
        git add .
        git commit -m "Get Solid data"
        git push
